theme: jekyll-theme-cayman
title: Learn Chinese Today
description: Learn Chinese with Dolores
github:
  page2: phrases.html
  page3: vocabulary.html
  page4: about-china.html
  page5: numbers.html
  page6: practice.html
